2025-08-07 14:53:22,127 - ERROR - Необработанное исключение: IndexError: list index out of range
2025-08-07 14:53:22,151 - ERROR - Трассировка стека:
Traceback (most recent call last):
  File "c:\Users\Alex\Competitions_TT_v1.1\main.py", line 3616, in tab_etap
    fill_table(player_list)
    ~~~~~~~~~~^^^^^^^^^^^^^
  File "c:\Users\Alex\Competitions_TT_v1.1\main.py", line 2734, in fill_table
    item_10 = str(list(player_selected[row].values())[num_columns[9]])
                                                      ~~~~~~~~~~~^^^
IndexError: list index out of range
2025-08-07 14:53:26,527 - ERROR - Необработанное исключение: IndexError: list index out of range
2025-08-07 14:53:26,528 - ERROR - Трассировка стека:
Traceback (most recent call last):
  File "c:\Users\Alex\Competitions_TT_v1.1\main.py", line 7674, in filter_fin
    fill_table(player_list)
    ~~~~~~~~~~^^^^^^^^^^^^^
  File "c:\Users\Alex\Competitions_TT_v1.1\main.py", line 2734, in fill_table
    item_10 = str(list(player_selected[row].values())[num_columns[9]])
                                                      ~~~~~~~~~~~^^^
IndexError: list index out of range
2025-08-07 14:53:26,544 - ERROR - Необработанное исключение: IndexError: list index out of range
2025-08-07 14:53:26,544 - ERROR - Трассировка стека:
Traceback (most recent call last):
  File "c:\Users\Alex\Competitions_TT_v1.1\main.py", line 10625, in choice_filter_on_system
    fill_table(player_list)
    ~~~~~~~~~~^^^^^^^^^^^^^
  File "c:\Users\Alex\Competitions_TT_v1.1\main.py", line 2734, in fill_table
    item_10 = str(list(player_selected[row].values())[num_columns[9]])
                                                      ~~~~~~~~~~~^^^
IndexError: list index out of range
2025-08-07 14:53:26,565 - ERROR - Необработанное исключение: IndexError: list index out of range
2025-08-07 14:53:26,567 - ERROR - Трассировка стека:
Traceback (most recent call last):
  File "c:\Users\Alex\Competitions_TT_v1.1\main.py", line 3616, in tab_etap
    fill_table(player_list)
    ~~~~~~~~~~^^^^^^^^^^^^^
  File "c:\Users\Alex\Competitions_TT_v1.1\main.py", line 2734, in fill_table
    item_10 = str(list(player_selected[row].values())[num_columns[9]])
                                                      ~~~~~~~~~~~^^^
IndexError: list index out of range
2025-08-07 14:53:28,426 - ERROR - Необработанное исключение: IndexError: list index out of range
2025-08-07 14:53:28,427 - ERROR - Трассировка стека:
Traceback (most recent call last):
  File "c:\Users\Alex\Competitions_TT_v1.1\main.py", line 10625, in choice_filter_on_system
    fill_table(player_list)
    ~~~~~~~~~~^^^^^^^^^^^^^
  File "c:\Users\Alex\Competitions_TT_v1.1\main.py", line 2734, in fill_table
    item_10 = str(list(player_selected[row].values())[num_columns[9]])
                                                      ~~~~~~~~~~~^^^
IndexError: list index out of range
2025-08-07 14:53:28,436 - ERROR - Необработанное исключение: IndexError: list index out of range
2025-08-07 14:53:28,436 - ERROR - Трассировка стека:
Traceback (most recent call last):
  File "c:\Users\Alex\Competitions_TT_v1.1\main.py", line 10625, in choice_filter_on_system
    fill_table(player_list)
    ~~~~~~~~~~^^^^^^^^^^^^^
  File "c:\Users\Alex\Competitions_TT_v1.1\main.py", line 2734, in fill_table
    item_10 = str(list(player_selected[row].values())[num_columns[9]])
                                                      ~~~~~~~~~~~^^^
IndexError: list index out of range
2025-08-07 14:53:28,461 - ERROR - Необработанное исключение: IndexError: list index out of range
2025-08-07 14:53:28,463 - ERROR - Трассировка стека:
Traceback (most recent call last):
  File "c:\Users\Alex\Competitions_TT_v1.1\main.py", line 3616, in tab_etap
    fill_table(player_list)
    ~~~~~~~~~~^^^^^^^^^^^^^
  File "c:\Users\Alex\Competitions_TT_v1.1\main.py", line 2734, in fill_table
    item_10 = str(list(player_selected[row].values())[num_columns[9]])
                                                      ~~~~~~~~~~~^^^
IndexError: list index out of range
