2025-08-06 11:36:52,215 - ERROR - Необработанное исключение: NameError: name 'chabge_pol' is not defined
2025-08-06 11:36:52,236 - ERROR - Трассировка стека:
Traceback (most recent call last):
  File "c:\Users\Alex\Competitions_TT_v1.1\main.py", line 1289, in open
    go_to()
    ~~~~~^^
  File "c:\Users\Alex\Competitions_TT_v1.1\main.py", line 2105, in go_to
    if flag_para == 0 and chabge_pol == 1:
                          ^^^^^^^^^^
NameError: name 'chabge_pol' is not defined
