2025-08-02 11:49:42,420 - ERROR - Необработанное исключение: IndexError: list index out of range
2025-08-02 11:49:42,421 - ERROR - Трассировка стека:
Traceback (most recent call last):
  File "c:\Users\Alex\Competitions_TT_v1.1\main.py", line 2213, in r_list_load_tableView
    fill_table_R_list()
    ~~~~~~~~~~~~~~~~~^^
  File "c:\Users\Alex\Competitions_TT_v1.1\main.py", line 2941, in fill_table_R_list
    fill_table(player_list)
    ~~~~~~~~~~^^^^^^^^^^^^^
  File "c:\Users\Alex\Competitions_TT_v1.1\main.py", line 2728, in fill_table
    item_8 = str(list(player_selected[row].values())[num_columns[7]])
                                                     ~~~~~~~~~~~^^^
IndexError: list index out of range
2025-08-02 11:49:43,153 - ERROR - Необработанное исключение: IndexError: list index out of range
2025-08-02 11:49:43,153 - ERROR - Трассировка стека:
Traceback (most recent call last):
  File "c:\Users\Alex\Competitions_TT_v1.1\main.py", line 702, in r1_File
    fill_table_R1_list()
    ~~~~~~~~~~~~~~~~~~^^
  File "c:\Users\Alex\Competitions_TT_v1.1\main.py", line 2955, in fill_table_R1_list
    fill_table(player_list)
    ~~~~~~~~~~^^^^^^^^^^^^^
  File "c:\Users\Alex\Competitions_TT_v1.1\main.py", line 2728, in fill_table
    item_8 = str(list(player_selected[row].values())[num_columns[7]])
                                                     ~~~~~~~~~~~^^^
IndexError: list index out of range
2025-08-02 11:49:50,254 - ERROR - Необработанное исключение: IndexError: list index out of range
2025-08-02 11:49:50,254 - ERROR - Трассировка стека:
Traceback (most recent call last):
  File "c:\Users\Alex\Competitions_TT_v1.1\main.py", line 694, in r_File
    fill_table_R_list()
    ~~~~~~~~~~~~~~~~~^^
  File "c:\Users\Alex\Competitions_TT_v1.1\main.py", line 2941, in fill_table_R_list
    fill_table(player_list)
    ~~~~~~~~~~^^^^^^^^^^^^^
  File "c:\Users\Alex\Competitions_TT_v1.1\main.py", line 2728, in fill_table
    item_8 = str(list(player_selected[row].values())[num_columns[7]])
                                                     ~~~~~~~~~~~^^^
IndexError: list index out of range
